function configs = preprocessPipeline_config()
% PREPROCESSPIPELINE_CONFIG Configuration templates for preprocessPipeline
%
% This function returns example configuration structures for common preprocessing
% workflows using dwim.preprocessPipeline().
%
% Usage:
%   cfgs = dwim.preprocessPipeline_config();
%   [volume, metadata] = dwim.preprocessPipeline('dicom_series/', cfgs.config_3d_volume);

%% Basic 2D Image Processing
configs.config_2d_basic = struct(...
    'inputType', 'filepath', ...
    'outputType', 'image', ...
    'steps', {{'validate', 'window', 'normalize'}}, ...
    'parameters', struct(...
        'window', struct('preset', 'lung'), ...
        'validate', struct() ...
    ), ...
    'validation', struct('enabled', true), ...
    'verbose', true ...
);

%% 3D Volume from DICOM Directory
configs.config_3d_volume = struct(...
    'inputType', 'dicomdir', ...
    'outputType', 'volume', ...
    'steps', {{'assemble', 'orient', 'resample', 'validate_volume'}}, ...
    'parameters', struct(...
        'orient', struct('targetOrientation', 'RAS'), ...
        'resample', struct('targetSpacing', 1.0), ...
        'validate_volume', struct() ...
    ), ...
    'validation', struct('enabled', true), ...
    'verbose', true ...
);

%% Full Pipeline (DICOM → Processed Volume)
configs.config_full_pipeline = struct(...
    'inputType', 'dicomdir', ...
    'outputType', 'volume', ...
    'steps', {{'assemble', 'orient', 'normalize', 'window', 'resample', 'validate_volume'}}, ...
    'parameters', struct(...
        'orient', struct('targetOrientation', 'RAS'), ...
        'normalize', struct(), ...
        'window', struct('preset', 'lung'), ...
        'resample', struct('targetSpacing', 1.0), ...
        'validate_volume', struct() ...
    ), ...
    'validation', struct('enabled', true), ...
    'verbose', true ...
);

%% Minimal Processing
configs.config_minimal = struct(...
    'inputType', 'image', ...
    'outputType', 'image', ...
    'steps', {{}}, ...  % No processing steps
    'parameters', struct(), ...
    'validation', struct('enabled', false), ...
    'verbose', false ...
);

%% Custom Research Pipeline
configs.config_research = struct(...
    'inputType', 'volume', ...
    'outputType', 'volume', ...
    'steps', {{'resample', 'validate_volume'}}, ...
    'parameters', struct(...
        'resample', struct('targetSpacing', 0.5), ...  % High resolution
        'validate_volume', struct('MinSlices', 50) ...  % Stricter validation
    ), ...
    'validation', struct('enabled', true), ...
    'verbose', true ...
);

end

%% Usage Examples
%
% % Load configs
% cfgs = dwim.preprocessPipeline_config();
%
% % Process a single DICOM file
% [processedImage, metadata] = dwim.preprocessPipeline('scan.dcm', cfgs.config_2d_basic);
%
% % Process DICOM series to 3D volume
% [volume, metadata] = dwim.preprocessPipeline('dicom_series/', cfgs.config_3d_volume);
%
% % Minimal processing on already loaded data
% [output, metadata] = dwim.preprocessPipeline(myImageArray, cfgs.config_minimal);